# Uncomment this line to define a global platform for your project

plugin 'cocoapods-art', :sources => [
  'cc-cocoapods-release-local',
  'trunk'
]

platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :tag => '7.5.0'
  pod 'JWTDecode', :git => 'https://github.com/auth0/JWTDecode.iOS.git', :tag => '2.6.3'
  pod 'Analytics', :git => 'https://github.com/segmentio/analytics-ios'
  pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire', :tag => '5.6.1'
  pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON', :tag => '4.0.0'
  pod 'JGProgressHUD', :git => 'https://github.com/JonasGessner/JGProgressHUD', :tag => '2.1.0'
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end


post_install do |installer|
 installer.pods_project.targets.each do |target|
   flutter_additional_ios_build_settings(target)
   target.build_configurations.each do |config|
     config.build_settings['ENABLE_BITCODE'] = 'NO'
     config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
     config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
     config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.1'
   end
 end
end
